### ISSUE TITLE
Sending to same user multiple times?

### ISSUE THREAD

**Issue by CssHammer** [hoemotion/Discord-Mass-DM#10]
Hi, saw the same issue here and it was marked as fixed, but i still have it. I'm wondering whether it printing issue or API calls are also being repeated? Haven't noticed any issues while debugging the loop. Thank you

![image](https://user-images.githubusercontent.com/8061508/147881085-4679811a-2270-4197-b5ed-d96a2d3b9c30.png)

**Comment by hoemotion** [comment]
the server verification level might be too high or its a community server try it with a non community server again
