### ISSUE TITLE
i just made the stars 75

### ISSUE THREAD

**Issue by ophidian-droid** [hoemotion/discord-mass-dm#12]
NOW GET THE F TO WORK

**Comment by hoemotion** [comment]
> NOW GET THE F TO WORK

It is already working, as i mentioned in my readme im taking a break currently
so the features might be added in 1-2 weeks

**Comment by babydoll323** [comment]
But I suck at this :( idk how to code lol I will try my hardest ok


Sent from Yahoo Mail for iPhone


On Tuesday, January 11, 2022, 11:44 PM, karma.meme ***@***.***> wrote:





NOW GET THE F TO WORK


It is already working, as i mentioned in my readme im taking a break currently
so the features might be added in 1-2 weeks

**Comment by hoemotion** [comment]
> 

I will reopen my guilded support server soon (old one has been terminated)

**Comment by hoemotion** [comment]
everything should be working now if not join my guilded server https://guilded.gg/karma and tell me your problem
