### ISSUE TITLE
banned by discord

### ISSUE THREAD

**Issue by jis0324** [hoemotion/discord-mass-dm#13]
Hello, @hoemotion 
At first, I appreciate you built/published good repo.
I just found this repo, and tested it for a day.
but omg... my 5 accounts were banned. k
Basically, I know the DM has limitations and it is 10 in 10 mins.
So I set the delay time to 70 seconds, and tried with a server that has about 700 members.
but after creating about 70 DM, my all accounts(were verified) were banned.
Could you let me know how we can handle this problem?
Regards

**Comment by hoemotion** [comment]
if you were using bad proxies or your accounts were already sus or just got caught by a ban wave its nothing special.
there is no way to avoid acc bans as they'll all get banned, some of them fast some of them slow

**Comment by jis0324** [comment]
@hoemotion Thanks for your quick response.
I did not use a proxy so far.
maybe, this option will help to avoid banning, to prolong lifetime of tokens?

**Comment by hoemotion** [comment]
yes it might help

**Comment by jis0324** [comment]
I see.
so there is no any way that we can prevent banning except proxy option. is right?
How many DM do you recommend per day in order to prevent banning of account?

**Comment by hoemotion** [comment]
> I see.
> so there is no any way that we can prevent banning except proxy option. is right?
> How many DM do you recommend per day in order to prevent banning of account?

idk how to add websockets to this shit so yeah if you know coding you can add this and create a pull request
avg dms of one acc shouldnt be more than 50 each day
