### ISSUE TITLE
Error while trying to use embed message.

### ISSUE THREAD

**Issue by JeanCarlig** [hoemotion/Discord-Mass-DM#2]
![issue](https://user-images.githubusercontent.com/95511766/146468939-84c73d3d-32f4-42eb-9a75-3fff2de60966.PNG)

You could try fixing it this way, I suppose it will work:
file = open(filename, encoding="utf8")

edit: this has to do with emojis I suppose, try to implement something for emojis, idk if UTF8 works.

**Comment by hoemotion** [comment]
Your json isnt correctly formatted it isnt something with the emojis
Join https://guilded.gg/hoemotion if you need help regarding the json formatting
