### ISSUE TITLE
doesnt do anythijng after submitting the delay time

### ISSUE THREAD

**Issue by XWapixelX** [hoemotion/discord-mass-dm#21]
![image](https://user-images.githubusercontent.com/99325121/153205351-b8d85538-0a57-4f15-9596-21c205bb31d2.png)
 this happens after I put everything in it correctly, even with proxies or without its just after the delay thingy its loading for ever without doing anything, any ideas? I tried with the message link thing and everything but still no luck.

**Comment by XWapixelX** [comment]
Yeah and the proxies are working and all so I dont know whats the Issue, Maybe u could help me?

**Comment by hoemotion** [comment]
> Yeah and the proxies are working and all so I dont know whats the Issue, Maybe u could help me?

Strange it should work.. 
join https://guilded.gg/karma and let me try helping you

**Comment by hoemotion** [comment]
Issue was solved in my server, it was a strange python issue which was solved by using a vm
