### ISSUE TITLE
Convert into exe 

### ISSUE THREAD

**Issue by aditya-pushkar** [hoemotion/discord-mass-dm#22]
Hey, 
i really want to convert this into EXECUTABLE file that can run without any dependency on any computer . I used pyinstaller but it is giving me path error every time

If possible point me to some good resource .

Thanks

**Comment by hoemotion** [comment]
check out [this](https://towardsdatascience.com/how-to-easily-convert-a-python-script-to-an-executable-file-exe-4966e253c7e9) guide
