### ISSUE TITLE
It stays blocked here

### ISSUE THREAD

**Issue by whoisbaby** [hoemotion/Discord-Mass-DM#4]
![image](https://user-images.githubusercontent.com/63604401/146763817-60d1f26d-9ef6-49af-8ec8-d58ccf133f38.png)

**Comment by hoemotion** [comment]
Have you waited 20 seconds? And try rerunning or running locally on your pc. You shouldnt have this error usually

**Comment by songbaizhi** [comment]
![image](https://user-images.githubusercontent.com/42461015/148671616-bb1e739e-51ff-44df-a798-a5b33eac0e5b.png)
I have the same problem

**Comment by hoemotion** [comment]
Its scraping the users, please wait a bit

**Comment by songbaizhi** [comment]
If the channel has 200,000 users, how long is the wait?

And what are Multiple Tokens? I don't quite understand this..
