### ISSUE TITLE
scrape only online members pls and dont scrape people with admin perms 

### ISSUE THREAD

**Issue by whoisbaby** [hoemotion/Discord-Mass-DM#5]

**Comment by whoisbaby** [comment]
and make to dont dm same user

**Comment by hoemotion** [comment]
> and make to dont dm same user all tokens

It shouldnt dm the same user but i will check it out and avoiding admins will be possible with the blacklist roles feature, also discum only scrapes only users if the server has 1k+ members

**Comment by whoisbaby** [comment]
you tested?

**Comment by hoemotion** [comment]
> you tested?
> and please make the updates there is 36 stars..

Yes i tested it and it worked fine for me but ill take a look at it again

**Comment by whoisbaby** [comment]
and blacklist role support when it comes

**Comment by hoemotion** [comment]
> and blacklist role support when it comes

This friday or weekend together with the proxy support

**Comment by hoemotion** [comment]
> and blacklist role support when it comes

Added role blacklisting feature proxies will come out in a fe day
