### ISSUE TITLE
New project if you want

### ISSUE THREAD

**Issue by whoisbaby** [hoemotion/Discord-Mass-DM#8]
can you do a discord vanity url spammer?
with random user agent and proxies?
which spam every 1 ms and dont get ratelimit

**Comment by hoemotion** [comment]
> can you do a discord vanity url spammer?
> with random user agent and proxies?
> which spam every 1 ms and dont get ratelimit

wdym by spammer, spamming the link in a channel?
also spamming messages that fast isnt possible

**Comment by whoisbaby** [comment]
no

**Comment by whoisbaby** [comment]
i send you a example wait

**Comment by whoisbaby** [comment]
async function req_url() {
  await req(`https://discord.com/api/v8/guilds/${client.config.GuildID}/vanity-url`, {
    "credentials": "include",
      "headers": { "accept": "*/*", "authorization": "Bot " + client.config.Bot_Token, "content-type": "application/json", },
       "referrerPolicy": "no-referrer-when-downgrade",
       "body": "vanityurl",
       "method": "PATCH",
       "mode": "cors"
 });
}
and a setinterval which spam every 1ms but this script is getting ratelimited after 4-5 request

**Comment by hoemotion** [comment]
> async function req_url() {
> await req(`https://discord.com/api/v8/guilds/${client.config.GuildID}/vanity-url`, {
> "credentials": "include",
> "headers": { "accept": "_/_", "authorization": "Bot " + client.config.Bot_Token, "content-type": "application/json", },
> "referrerPolicy": "no-referrer-when-downgrade",
> "body": "vanityurl",
> "method": "PATCH",
> "mode": "cors"
> });
> }
> and a setinterval which spam every 1ms but this script is getting ratelimited after 4-5 request

I still dont know what you mean by a vanity spammer does this change the server vanity or what

**Comment by whoisbaby** [comment]
yes

**Comment by whoisbaby** [comment]
like a server vanity protector

**Comment by whoisbaby** [comment]
im sure you can do this shit in 5 minutes

**Comment by whoisbaby** [comment]
i have a vanity sniper with python and i can send it in dm on discord if you want

**Comment by whoisbaby** [comment]
@hoemotion
