### ISSUE TITLE
Crashes while attempting to join the server

### ISSUE THREAD

**Issue by deman2660** [hoemotion/Discord-Mass-DM#9]
when it says "joining server" it crashes and closes.

**Comment by hoemotion** [comment]
> when it says "joining server" it crashes and closes.

Have you entered the invite code correctly?

**Comment by deman2660** [comment]
i do believe so, 
![image](https://user-images.githubusercontent.com/73039800/147603882-217e626c-dbfe-4661-9c90-2efc7fb9974a.png)
this is what it looks like, could the error have something to do with it?

**Comment by hoemotion** [comment]
> i do believe so,
> ![image](https://user-images.githubusercontent.com/73039800/147603882-217e626c-dbfe-4661-9c90-2efc7fb9974a.png)
> this is what it looks like, could the error have something to do with it?

Is your asyncio on the latest? If not try updating it

**Comment by deman2660** [comment]
I updated it and it hasnt changed anything

**Comment by hoemotion** [comment]
> I updated it and it hasnt changed anything

Strange have you got this error on [repl.it](https://repl.it) too?

**Comment by deman2660** [comment]
Yes

**Comment by hoemotion** [comment]
Hold up i think its your 1000 seconds delay which causes this issue the asyncio message is just a warning which can be ignored have you waited 10k seconds? 💀

**Comment by deman2660** [comment]
bro. i thought it was in milliseconds.
god fucking damn it

**Comment by deman2660** [comment]
well. new error now
![image](https://user-images.githubusercontent.com/73039800/147605667-a34345c9-46e7-4100-affa-297535462cee.png)
even tho the json is there with that exact name

**Comment by hoemotion** [comment]
> well. new error now
> ![image](https://user-images.githubusercontent.com/73039800/147605667-a34345c9-46e7-4100-affa-297535462cee.png)
> even tho the json is there with that exact name

Changed the code a lil bit try again and tell me if it worked

**Comment by deman2660** [comment]
![image](https://user-images.githubusercontent.com/73039800/147607177-21186e11-286e-4016-b9c6-14891850a8db.png)
still isnt working and not sure why

**Comment by hoemotion** [comment]
> 

Oof okay i guess its searching for the file from the root so where main.py is try moving the file to the root and tell me if it worked 😦

**Comment by deman2660** [comment]
YO THANK YOU, that worked
